accuracy_coeff: 0.98
utilisation_coeff: 0.02
batch_size: 1024
checkpoint: null
crossover_prob: 0.5
cuda: true
dataset_file: unsw_nb15_binarized.npz
elitism: 1
epochs: 25
evo_log_file_path: evo_logs/evo_0.txt
evo_pickle_path: nas_pickle/acc_0.98_util_0.02_hl_4_10_40.pkl
evo_seed_path: nas_pickle/seed0.pkl
gene_crossover_prob: 0.2
gene_mutation_prob: 0.3
grad_clear_logs: false
grad_log_file_path: nas_runs/grad_0.csv
grad_max_iterations: 100
hidden_layers: 4
learning_rate: 0.1
log_dir: training-logs
max_bitwidth: 2
max_fanin: 7
max_generations: 40
max_layer_size: 593
min_bitwidth: 1
min_fanin: 3
min_layer_size: 5
mode: evo
mutation_prob: 0.4
pop_size: 10
randoms: 1
seed: null
target_accuracy: 0.92
tourn_size: 2
unity_utilisation: 757850
weight_decay: 0.0
